name: ESLint
on:
  push:
    branches:
      - master
jobs:
  publish:
    name: Install and linting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 14.x
      # - uses: expo/expo-github-action@v5
      #   with:
      #     expo-version: 3.x
          # expo-username: ${{ secrets.EXPO_CLI_USERNAME }}
          # expo-password: ${{ secrets.EXPO_CLI_PASSWORD }}
      - run: npm install
      - run: npm run lint
      # - run: expo publish
